### ISSUE TITLE
rules are not undeployed using undeploy script/command

### ISSUE THREAD

**Issue by Himavanth** [adobe/aio-app-scripts#119]
Sample manifest: 
```
packages:
  __APP_PACKAGE__:
    license: Apache-2.0
    actions:
      report:
        function: /Users/himar/hello.js
        runtime: 'nodejs:10'
    triggers:
      everyMinute:
        feed: /whisk.system/alarms/alarm
        inputs:
          cron: "* * * * *"
          trigger_payload: "{\"message\": \"hello world!\"}"
    rules:
      reportEveryMinute:
        action: report
        trigger: everyMinute
```
It seems rules cannot be annotated and hence they cannot be fetched to undeploy.
Rules should be fetched the same way APIs are fetched from the manifest.
### Expected Behaviour
rules should be undeployed
### Actual Behaviour
rules are not undeployed
